import p from './p.jpg'

export const obj = {
    "login": "dave",
    "id": 925351,
    "node_id": "MDQ6VXNlcjkyNTM1MQ==",
    "avatar_url": p,
    "gravatar_id": "",
    "url": "https://api.github.com/users/dave",
    "html_url": "https://github.com/dave",
    "followers_url": "https://api.github.com/users/dave/followers",
    "following_url": "https://api.github.com/users/dave/following{/other_user}",
    "gists_url": "https://api.github.com/users/dave/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dave/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dave/subscriptions",
    "organizations_url": "https://api.github.com/users/dave/orgs",
    "repos_url": "https://api.github.com/users/dave/repos",
    "events_url": "https://api.github.com/users/dave/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dave/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Dave Brophy",
    "company": null,
    "blog": "https://www.wildernessprime.com/",
    "location": "Germany",
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 117,
    "public_gists": 12,
    "followers": 215,
    "following": 1,
    "created_at": "2011-07-19T13:04:55Z",
    "updated_at": "2021-07-15T17:31:21Z"
}